# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [ ]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr2d = arr1d.reshape(3, 4)
print("Reshaped 2D array:")
print(arr2d)

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])


arr_horizontal = np.concatenate((arr1, arr2), axis=1)
print("\nConcatenated horizontally array:")
print(arr_horizontal)

arr_vertical = np.concatenate((arr1, arr2), axis=0)
print("\nConcatenated vertically array:")
print(arr_vertical)

Reshaped 2D array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Concatenated horizontally array:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

Concatenated vertically array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [ ]:
def classify_emails(emails):
    important_keywords = ["important", "urgent", "critical"]
    promotions_keywords = ["promotions", "deals", "discount"]
    spam_keywords = ["lottery", "free gift", "claim your prize"]

    important_emails = []
    promotions_emails = []
    spam_emails = []

    for email in emails:
        if any(keyword in email.lower() for keyword in important_keywords):
            important_emails.append(email)
        elif any(keyword in email.lower() for keyword in promotions_keywords):
            promotions_emails.append(email)
        elif any(keyword in email.lower() for keyword in spam_keywords):
            spam_emails.append(email)

    return important_emails, promotions_emails, spam_emails

# Sample list of emails
sample_emails = [
    "This is an important message.",
    "Get 50% off on all products!",
    "You have won a free vacation package!",
    "Urgent: Action required on your account."
]

important, promotions, spam = classify_emails(sample_emails)

# Print the lists
print("Important Emails:")
print(important)
print("\nPromotions Emails:")
print(promotions)
print("\nSpam Emails:")
print(spam)

Important Emails:
['This is an important message.', 'Urgent: Action required on your account.']

Promotions Emails:
[]

Spam Emails:
[]


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [ ]:
english_spanish_dict = {
    "hello": "hola",
    "goodbye": "adiós",
    "cat": "gato",
    "dog": "perro",
    "house": "casa"
}

while True:

    user_input = input("Enter an English word (or 'exit' to quit): ")

    # Check if the user wants to exit
    if user_input.lower() == "exit":
        print("Goodbye!")
        break

    # Check if the word exists in the dictionary
    if user_input in english_spanish_dict:
        print(f"The Spanish translation of '{user_input}' is '{english_spanish_dict[user_input]}'.")
    else:
        print(f"The translation of '{user_input}' is not available.")


Enter an English word (or 'exit' to quit): hello
The Spanish translation of 'hello' is 'hola'.
Enter an English word (or 'exit' to quit): goodbye
The Spanish translation of 'goodbye' is 'adiós'.
Enter an English word (or 'exit' to quit): quit
The translation of 'quit' is not available.
Enter an English word (or 'exit' to quit): exit
Goodbye!


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [1]:
import pandas as pd

# Reading the dataset
url = 'https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv'
game_data = pd.read_csv(url)

In [2]:

total_global_sales = game_data['Global_Sales'].sum()
print("Total Global Sales:", total_global_sales, "million")


game_highest_sales = game_data.loc[game_data['Global_Sales'].idxmax()]
print("Game with the Highest Global Sales:")
print(game_highest_sales)

average_sales_per_region = game_data[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print("Average Sales for Each Region:")
print(average_sales_per_region)


top_5_genres_global_sales = game_data.groupby('Genre')['Global_Sales'].sum().nlargest(5)
print("Top 5 Most Popular Game Genres Based on Global Sales:")
print(top_5_genres_global_sales)


total_sales_per_genre_region = game_data.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
print("Total Sales for Each Genre in Each Region and the Most Popular Genre in North America (NA_Sales):")

most_popular_genre_na = total_sales_per_genre_region['NA_Sales'].idxmax()

print("Most popular genre in North America based on sales:", most_popular_genre_na)


last_10_rows = game_data.tail(10)
print("Last 10 Rows:")
print(last_10_rows)


top_3_platforms_global_sales = game_data.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print("Top 3 Gaming Platforms with the Highest Global Sales:")
print(top_3_platforms_global_sales)


market_share_per_genre = (game_data.groupby('Genre')['Global_Sales'].sum() / game_data['Global_Sales'].sum()) * 100
print("Market Share for Each Genre:")
print(market_share_per_genre)


correlation_coefficient = game_data['NA_Sales'].corr(game_data['EU_Sales'])
print("Correlation Coefficient between NA_Sales and EU_Sales:", correlation_coefficient)

Total Global Sales: 8920.44 million
Game with the Highest Global Sales:
Rank                     1
Name            Wii Sports
Platform               Wii
Year                2006.0
Genre               Sports
Publisher         Nintendo
NA_Sales             41.49
EU_Sales             29.02
JP_Sales              3.77
Other_Sales           8.46
Global_Sales         82.74
Name: 0, dtype: object
Average Sales for Each Region:
NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64
Top 5 Most Popular Game Genres Based on Global Sales:
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64
Total Sales for Each Genre in Each Region and the Most Popular Genre in North America (NA_Sales):
Most popular genre in North America based on sales: Action
Last 10 Rows:
        Rank                                               Name Platform  \
1658

Some tree example

In [ ]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [ ]:
# pip install networkx


In [ ]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))
